In [49]:
import numpy as np
import pandas as pd

In [111]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

In [85]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [67]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [2]:
flowers = load_iris()

In [3]:
dir(flowers)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [12]:
len(flowers.data)

150

In [17]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='scale'),flowers.data,flowers.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [21]:
cross_val_score(SVC(kernel='sigmoid',C=10,gamma='scale'),flowers.data,flowers.target,cv=5)

array([0.03333333, 0.16666667, 0.        , 0.06666667, 0.        ])

In [22]:
cross_val_score(SVC(kernel='linear',C=10,gamma='scale'),flowers.data,flowers.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [23]:
cross_val_score(SVC(kernel='poly',C=20,gamma='scale'),flowers.data,flowers.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

**We oberved that 'poly','linear','rbf' is good value in this case.**

In [39]:
kernel = ['poly','linear','rbf']
gamma = ['scale','auto']
for i in kernel:
    for j in gamma:
        score_list = cross_val_score(SVC(kernel=i,C=10,gamma=j),flowers.data,flowers.target,cv=5)
        print(i,j,score_list,np.mean(score_list))

poly scale [1.         1.         0.9        0.93333333 1.        ] 0.9666666666666666
poly auto [1.         1.         0.9        0.93333333 1.        ] 0.9666666666666666
linear scale [1.         1.         0.9        0.96666667 1.        ] 0.9733333333333334
linear auto [1.         1.         0.9        0.96666667 1.        ] 0.9733333333333334
rbf scale [0.96666667 1.         0.96666667 0.96666667 1.        ] 0.9800000000000001
rbf auto [0.96666667 1.         0.96666667 0.96666667 1.        ] 0.9800000000000001


In [46]:
hypertune = GridSearchCV(SVC(),{'gamma':['auto','scale'],"kernel":['rbf','linear','poly']})

In [47]:
hypertune.fit(flowers.data,flowers.target)

GridSearchCV(estimator=SVC(),
             param_grid={'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear', 'poly']})

In [48]:
hypertune.cv_results_

{'mean_fit_time': array([0.00286226, 0.        , 0.0016046 , 0.00179596, 0.0006093 ,
        0.0031312 ]),
 'std_fit_time': array([0.00074193, 0.        , 0.00185345, 0.00039742, 0.00080488,
        0.0062624 ]),
 'mean_score_time': array([0.00180407, 0.00308099, 0.00059724, 0.00101104, 0.00019879,
        0.        ]),
 'std_score_time': array([7.52210268e-04, 6.16197586e-03, 4.87657517e-04, 2.83506058e-05,
        3.97586823e-04, 0.00000000e+00]),
 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'scale', 'scale', 'scale'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'gamma': 'auto', 'kernel': 'rbf'},
  {'gamma': 'auto', 'kernel': 'linear'},
  {'gamma': 'auto', 'kernel': 'poly'},
  {'gamma': 's

In [50]:
df = pd.DataFrame(hypertune.cv_results_)

In [51]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_gamma  \
0       0.002862      0.000742         0.001804        0.000752        auto   
1       0.000000      0.000000         0.003081        0.006162        auto   
2       0.001605      0.001853         0.000597        0.000488        auto   
3       0.001796      0.000397         0.001011        0.000028       scale   
4       0.000609      0.000805         0.000199        0.000398       scale   
5       0.003131      0.006262         0.000000        0.000000       scale   

  param_kernel                                  params  split0_test_score  \
0          rbf      {'gamma': 'auto', 'kernel': 'rbf'}           0.966667   
1       linear   {'gamma': 'auto', 'kernel': 'linear'}           0.966667   
2         poly     {'gamma': 'auto', 'kernel': 'poly'}           1.000000   
3          rbf     {'gamma': 'scale', 'kernel': 'rbf'}           0.966667   
4       linear  {'gamma': 'scale', 'kernel': 'linear'}           0.966667   
5         poly    {'gamma': 'scale', 'kernel': 'poly'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           1.000000           0.900000           0.933333                1.0   
3           0.966667           0.966667           0.933333                1.0   
4           1.000000           0.966667           0.966667                1.0   
5           1.000000           0.966667           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.966667        0.042164                5  
3         0.966667        0.021082                5  
4         0.980000        0.016330                1  
5         0.980000        0.016330                1

In [54]:
df[['param_gamma','param_kernel','mean_test_score']].sort_values('mean_test_score')

param_gamma param_kernel  mean_test_score
2        auto         poly         0.966667
3       scale          rbf         0.966667
0        auto          rbf         0.980000
1        auto       linear         0.980000
4       scale       linear         0.980000
5       scale         poly         0.980000

In [55]:
dir(hypertune)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [58]:
hypertune.best_estimator_

SVC(gamma='auto')

In [65]:
hypertune.best_params_ 

{'gamma': 'auto', 'kernel': 'rbf'}

In [66]:
hypertune.best_score_ #Mean cross-validated score of the best_estimator

0.9800000000000001

In [78]:
random_tune = RandomizedSearchCV(SVC(),{'gamma':['auto','scale'],"kernel":['rbf','linear','poly']},cv=5,n_iter=3)

In [79]:
random_tune.fit(flowers.data,flowers.target)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=3,
                   param_distributions={'gamma': ['auto', 'scale'],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [80]:
df2 = pd.DataFrame(random_tune.cv_results_)

In [81]:
df2

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.002194      0.000747         0.001203        0.000412       linear   
1       0.002395      0.001018         0.000998        0.000002       linear   
2       0.001422      0.000773         0.000997        0.000001         poly   

  param_gamma                                  params  split0_test_score  \
0        auto   {'kernel': 'linear', 'gamma': 'auto'}           0.966667   
1       scale  {'kernel': 'linear', 'gamma': 'scale'}           0.966667   
2       scale    {'kernel': 'poly', 'gamma': 'scale'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0             0.98         0.01633                1  
1             0.98         0.01633                1  
2             0.98         0.01633                1

In [82]:
random_tune.best_score_

0.9800000000000001

In [83]:
random_tune.best_params_

{'kernel': 'linear', 'gamma': 'auto'}

**Choosing Best Model**

In [124]:
model_params = {
    'svm':{
        'model':SVC(),
           'params':{
        'kernel':['linear','poly','rbf'],
        'gamma':['auto','scale']}
    },
    'LogisticRegression':{'model':LogisticRegression(solver='lbfgs', max_iter=1000),
                          'params':{'C':[1,10,20]}
        
    },
    'RandomForestClassifier':{
        'model':RandomForestClassifier(),
        'params':{'n_estimators':[1,5,10]}
    }
}

In [127]:
scores = []
for model_name,mp in model_params.items():
    tune = GridSearchCV(mp['model'],mp['params'],cv=5)
    tune.fit(flowers.data,flowers.target)
    scores.append([model_name,tune.best_estimator_,tune.best_score_])

In [128]:
scores

[['svm', SVC(gamma='auto', kernel='linear'), 0.9800000000000001],
 ['LogisticRegression',
  LogisticRegression(C=20, max_iter=1000),
  0.9800000000000001],
 ['RandomForestClassifier',
  RandomForestClassifier(n_estimators=10),
  0.9533333333333334]]

**Based on the results, SVC with gamma = auto and kernel='linear' is best model with best parameter.**