In [2]:
import pandas as pd
from sklearn.decomposition import NMF
import numpy as np

In [3]:
df = pd.read_csv("diabetes.csv")

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [10]:
model = NMF(n_components=3)

In [11]:
df.shape

(768, 9)

In [12]:
transformed = model.fit_transform(df) # W _mtarix

In [13]:
transformed

array([[0.00702319, 1.38869913, 1.55937026],
       [0.00562954, 1.36229242, 0.88772257],
       [0.        , 0.77561587, 1.90859744],
       ...,
       [1.00669341, 1.34486235, 0.99286373],
       [0.        , 1.00750348, 1.3520634 ],
       [0.0082053 , 1.40666891, 0.95798922]], shape=(768, 3))

In [19]:
transformed.shape # W matrix

(768, 3)

In [20]:
matrix_H = model.components_

In [21]:
matrix_H

array([[0.00000000e+00, 2.54553821e+01, 0.00000000e+00, 5.53170391e+00,
        1.11282073e+02, 2.80834524e+00, 8.97907667e-02, 1.50298118e+00,
        8.59828621e-02],
       [1.27671903e+00, 1.82561145e-01, 4.31726773e+01, 1.28506333e+01,
        0.00000000e+00, 1.24647903e+01, 1.27305601e-01, 1.05261164e+01,
        0.00000000e+00],
       [2.03042638e+00, 9.49845268e+01, 1.17033423e+01, 0.00000000e+00,
        0.00000000e+00, 1.21560264e+01, 2.14229884e-01, 1.68174812e+01,
        2.96626119e-01]])

In [22]:
matrix_H.shape

(3, 9)

In [33]:
df_comp = pd.DataFrame(matrix_H,columns = df.columns)

In [34]:
df_comp

Pregnancies    Glucose  BloodPressure  SkinThickness     Insulin  \
0     0.000000  25.455382       0.000000       5.531704  111.282073   
1     1.276719   0.182561      43.172677      12.850633    0.000000   
2     2.030426  94.984527      11.703342       0.000000    0.000000   

         BMI  DiabetesPedigreeFunction        Age   Outcome  
0   2.808345                  0.089791   1.502981  0.085983  
1  12.464790                  0.127306  10.526116  0.000000  
2  12.156026                  0.214230  16.817481  0.296626

In [39]:
for i in range(0,3):
    print(df_comp.loc[i].nlargest(3))
    print("\n")
    

Insulin          111.282073
Glucose           25.455382
SkinThickness      5.531704
Name: 0, dtype: float64


BloodPressure    43.172677
SkinThickness    12.850633
BMI              12.464790
Name: 1, dtype: float64


Glucose    94.984527
Age        16.817481
BMI        12.156026
Name: 2, dtype: float64




In [25]:
re_v = np.dot(transformed,matrix_H)

In [26]:
re_v

array([[  4.93916512, 148.54834682,  78.2037034 , ...,   0.5114835 ,
         40.85284449,   0.46315382],
       [  3.54171998,  84.71191202,  69.20313214, ...,   0.36410964,
         29.27736732,   0.26380574],
       [  4.86551013, 181.428822  ,  55.82238282, ...,   0.50761885,
         40.26202454,   0.56613985],
       ...,
       [  3.73294806, 120.1779763 ,  69.68113244, ...,   0.47430136,
         32.36668597,   0.38106769],
       [  4.03156405, 128.609033  ,  59.32028336, ...,   0.41791322,
         33.34339969,   0.40105732],
       [  3.74104755,  91.45982474,  71.94133881, ...,   0.38504351,
         30.9300588 ,   0.28487014]], shape=(768, 9))

In [27]:
df_trans = pd.DataFrame(transformed) # Uses W matrix

In [32]:
df_trans

0         1         2
0    0.007023  1.388699  1.559370
1    0.005630  1.362292  0.887723
2    0.000000  0.775616  1.908597
3    0.846594  1.316185  0.698396
4    1.517836  0.866769  1.048088
..        ...       ...       ...
763  1.619888  1.839714  0.664334
764  0.006840  1.323390  1.268246
765  1.006693  1.344862  0.992864
766  0.000000  1.007503  1.352063
767  0.008205  1.406669  0.957989

[768 rows x 3 columns]

In [29]:
df_trans.describe()

0           1           2
count  768.000000  768.000000  768.000000
mean     0.719364    1.313991    1.078266
std      1.034007    0.396108    0.355275
min      0.000000    0.000000    0.000000
25%      0.000000    1.144528    0.829335
50%      0.278531    1.359069    1.048261
75%      1.147358    1.558920    1.288760
max      7.578148    2.367754    2.064707