In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [4]:
df.isna().sum()

town     0
area     0
price    0
dtype: int64

In [5]:
dummies = pd.get_dummies(df['town'],dtype= int) #Gives encoded data with integers

In [6]:
dummies 

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [7]:
df_merged = pd.concat([df,dummies],axis ='columns')

In [8]:
df_merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [9]:
df_merged.drop(columns='town',inplace = True)
#We do not need town column

In [10]:
df_merged.head()

area   price  monroe township  robinsville  west windsor
0  2600  550000                1            0             0
1  3000  565000                1            0             0
2  3200  610000                1            0             0
3  3600  680000                1            0             0
4  4000  725000                1            0             0

In [11]:
df_merged.drop(columns='west windsor',inplace = True)

In [12]:
model = LinearRegression()

In [13]:
model.fit(df_merged[['area','monroe township','robinsville']].values,df_merged['price'])

LinearRegression()

In [14]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [15]:
model.intercept_

249790.36766292533

In [16]:
model.predict([[2800,0,1]]) # robinsville 

array([590775.63964739])

In [17]:
model.predict([[2800,1,0]]) #monroe township

array([565089.22812299])

Note : monroe township coef < robinsville coef, then, price in monroe is less than robinsville for same area.

In [18]:
model.score(df_merged[['area','monroe township','robinsville']].values,df_merged['price'])

0.9573929037221873

In [19]:
# One Hot Encoding

In [20]:
le = LabelEncoder()

In [21]:
dflabel = df
dflabel['town'] = le.fit_transform(dflabel['town'])
dflabel

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [22]:
x = dflabel[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [23]:
y = dflabel['price'].values

In [24]:
# One Hot Encoding

In [25]:
ohe  = OneHotEncoder()

In [26]:
# Applies transformers to columns of an array or pandas DataFrame. (name, transformer, columns)

ct = ColumnTransformer([('ohe', OneHotEncoder(), [0])], remainder='passthrough')
# By default, only the specified columns in `transformers` are
#     transformed and combined in the output, and the non-specified
#     columns are dropped. (default of ``'drop'``).
#     By specifying ``remainder='passthrough'``, all remaining columns that
#     were not specified in `transformers`, but present in the data passed
#     to `fit` will be automatically passed through.

In [27]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe', OneHotEncoder(), [0])])

In [28]:
X = ct.fit_transform(x) #unlike previous case, ct contains Transformers details

In [29]:
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [30]:
# Removing dummy variable trap
X = X[:,1:]

In [31]:
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [32]:
model.fit(X,y)

LinearRegression()

In [33]:
model.predict([[1,0,2800]]) # 1 for robensivile 

array([590775.63964739])

Getting same price both from one hot encoding and dummy variables

In [34]:
df2 = pd.read_csv('carprices.csv')

In [35]:
df2.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [36]:
df2.isna().sum()

Car Model        0
Mileage          0
Sell Price($)    0
Age(yrs)         0
dtype: int64

In [37]:
dummies = pd.get_dummies(df2['Car Model'],dtype=int)

In [38]:
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [39]:
df2_merged = pd.concat([df2,dummies],axis = 'columns')

In [40]:
df2_merged.head()

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0    BMW X5    69000          18000         6        0       1   
1    BMW X5    35000          34000         3        0       1   
2    BMW X5    57000          26100         5        0       1   
3    BMW X5    22500          40000         2        0       1   
4    BMW X5    46000          31500         4        0       1   

   Mercedez Benz C class  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0

In [41]:
df2_merged.drop(columns=['Car Model','Mercedez Benz C class'],inplace = True)

In [42]:
df2_merged

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [43]:
model.fit(df2_merged[['Mileage','Age(yrs)','Audi A5','BMW X5']].values,df2_merged['Sell Price($)'])

LinearRegression()

In [44]:
model.predict([[35000,3,0,1]])

array([35286.78445645])

In [45]:
#One Hot Encoding

In [47]:
df2_label = df2
df2_label['Car Model'] = le.fit_transform(df2['Car Model'])
df2_label

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [48]:
ct = ColumnTransformer([('ohe', OneHotEncoder(), [0])], remainder='passthrough')

In [51]:
X = ct.fit_transform(df2_label[['Car Model','Mileage','Age(yrs)']].values)

In [52]:
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [53]:
X = X[:,1:]

In [54]:
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [56]:
model.fit(X,df2_label['Sell Price($)'])

LinearRegression()

In [57]:
model.predict([[1,0,35000,3]]) #Same price

array([35286.78445645])